FROM postgres

COPY db_data/init_dbs.sh /docker-entrypoint-initdb.d/
RUN  sed -i -e 's/\r$//' /docker-entrypoint-initdb.d/init_dbs.sh

RUN mkdir /db_schemas
COPY ./db_data/conta_schema.sql /db_schemas/schema.sql